export const PlayListActionTypes = {
  ADD_VIDEO: 'ADD_VIDEO',
  START_FROM_BEGINNING: 'START_FROM_BEGINNING',
  SET_NEXT_VIDEO: 'SET_NEXT_VIDEO',
  SET_PLAYING: 'SET_PLAYING',
  CHANGE_ORDER: 'CHANGE_ORDER',
  DELETE_VIDEO: 'DELETE_VIDEO'
}